project:
  type: website
  output-dir: _site
  render:
    - proposal.qmd

website:
  title: "SG CPI Forecast"
  navbar:
    left:
      - text: "Proposal"
        href: proposal.qmd

format:
  html:
    toc: true
    number-sections: true

execute:
  echo: true
  warning: false
  message: false
  cache: true
  freeze: auto